clear;
load('duke_test.mat');
load('duke_attribute.mat')
sizen = size(test,1);
txt  = fopen('duke_test_attr.txt', 'wt');
for i = 1:sizen
    
    id = test{i, 2};

    fprintf(txt, '%s%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d\n',...
        test{i,1}, ...
        ' ', duke_attribute.test.backpack(id) -1,...
        ' ', duke_attribute.test.bag(id) -1,...
        ' ', duke_attribute.test.handbag(id) -1,...
        ' ', duke_attribute.test.boots(id) -1,...
        ' ', duke_attribute.test.gender(id) -1,...
        ' ', duke_attribute.test.hat(id) -1,...
        ' ', duke_attribute.test.shoes(id) -1,...
        ' ', duke_attribute.test.top(id) -1,...
        ' ', duke_attribute.test.downblack(id) -1,...
        ' ', duke_attribute.test.downwhite(id) -1,...
        ' ', duke_attribute.test.downred(id) -1,...
        ' ', duke_attribute.test.downgray(id) -1,...
        ' ', duke_attribute.test.downblue(id) -1,...
        ' ', duke_attribute.test.downgreen(id) -1,...
        ' ', duke_attribute.test.downbrown(id) -1,...
        ' ', duke_attribute.test.upblack(id) -1,...
        ' ', duke_attribute.test.upwhite(id) -1,...
        ' ', duke_attribute.test.upred(id) -1,...
        ' ', duke_attribute.test.uppurple(id) -1,...
        ' ', duke_attribute.test.upgray(id) -1,...
        ' ', duke_attribute.test.upblue(id) -1,...
        ' ', duke_attribute.test.upgreen(id) -1,...
        ' ', duke_attribute.test.upbrown(id) -1);
    
end
fclose(txt);
