clear;
load('market_test.mat');
load('market_attribute.mat')
sizen = size(test,1);
txt  = fopen('market_test_attr.txt', 'wt');
for i = 1:sizen
    
    id = test{i, 2};

    fprintf(txt, '%s%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d\n',...
        test{i,1}, ...
        ' ', market_attribute.test.age(id) - 1,...
        ' ', market_attribute.test.backpack(id) - 1,...
        ' ', market_attribute.test.bag(id) - 1,...
        ' ', market_attribute.test.handbag(id) - 1,...
        ' ', market_attribute.test.downblack(id) - 1,...
        ' ', market_attribute.test.downblue(id) - 1,...
        ' ', market_attribute.test.downbrown(id) - 1,...
        ' ', market_attribute.test.downgray(id) - 1,...
        ' ', market_attribute.test.downgreen(id) - 1,...
        ' ', market_attribute.test.downpink(id) - 1,...
        ' ', market_attribute.test.downpurple(id) - 1,...
        ' ', market_attribute.test.downwhite(id) - 1,...
        ' ', market_attribute.test.downyellow(id) - 1,...
        ' ', market_attribute.test.upblack(id) - 1,...
        ' ', market_attribute.test.upblue(id) - 1,...
        ' ', market_attribute.test.upgreen(id) - 1,...
        ' ', market_attribute.test.upgray(id) - 1,...
        ' ', market_attribute.test.uppurple(id) - 1,...
        ' ', market_attribute.test.upred(id) - 1,...
        ' ', market_attribute.test.upwhite(id) - 1,...
        ' ', market_attribute.test.upyellow(id) - 1,...
        ' ', market_attribute.test.clothes(id) - 1,...
        ' ', market_attribute.test.down(id) - 1,...
        ' ', market_attribute.test.up(id) - 1,...
        ' ', market_attribute.test.hair(id) - 1,...
        ' ', market_attribute.test.hat(id) - 1,...
        ' ', market_attribute.test.gender(id) - 1);
    
end
fclose(txt);
