clear;
load('market_test.mat');
load('market_attribute.mat')
txt  = fopen('test_attr.txt', 'wt');
for i = 1:13115
    
    id = test{i, 2};

    fprintf(txt, '%s%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d\n',...
        test{i,1}, ...
        ' ', market_attribute.test.age(id),...
        ' ', market_attribute.test.backpack(id),...
        ' ', market_attribute.test.bag(id),...
        ' ', market_attribute.test.handbag(id),...
        ' ', market_attribute.test.downblack(id),...
        ' ', market_attribute.test.downblue(id),...
        ' ', market_attribute.test.downbrown(id),...
        ' ', market_attribute.test.downgray(id),...
        ' ', market_attribute.test.downgreen(id),...
        ' ', market_attribute.test.downpink(id),...
        ' ', market_attribute.test.downpurple(id),...
        ' ', market_attribute.test.downwhite(id),...
        ' ', market_attribute.test.downyellow(id),...
        ' ', market_attribute.test.upblack(id),...
        ' ', market_attribute.test.upblue(id),...
        ' ', market_attribute.test.upgreen(id),...
        ' ', market_attribute.test.upgray(id),...
        ' ', market_attribute.test.uppurple(id),...
        ' ', market_attribute.test.upred(id),...
        ' ', market_attribute.test.upwhite(id),...
        ' ', market_attribute.test.upyellow(id),...
        ' ', market_attribute.test.clothes(id),...
        ' ', market_attribute.test.down(id),...
        ' ', market_attribute.test.up(id),...
        ' ', market_attribute.test.hair(id),...
        ' ', market_attribute.test.hat(id),...
        ' ', market_attribute.test.gender(id));
    
end
fclose(txt);
