clear;
load('market_train.mat');
load('market_attribute.mat')
sizen = size(train,1);
txt  = fopen('market_train_id_attr.txt', 'wt');
for i = 1:sizen
    
    id = train{i, 2};
    label = id - 1;

    fprintf(txt, '%s%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d%s%d\n',...
        train{i,1}, ...
        ' ', label,...
        ' ', market_attribute.train.age(id) - 1,...
        ' ', market_attribute.train.backpack(id) - 1,...
        ' ', market_attribute.train.bag(id) - 1,...
        ' ', market_attribute.train.handbag(id) - 1,...
        ' ', market_attribute.train.downblack(id) - 1,...
        ' ', market_attribute.train.downblue(id) - 1,...
        ' ', market_attribute.train.downbrown(id) - 1,...
        ' ', market_attribute.train.downgray(id) - 1,...
        ' ', market_attribute.train.downgreen(id) - 1,...
        ' ', market_attribute.train.downpink(id) - 1,...
        ' ', market_attribute.train.downpurple(id) - 1,...
        ' ', market_attribute.train.downwhite(id) - 1,...
        ' ', market_attribute.train.downyellow(id) - 1,...
        ' ', market_attribute.train.upblack(id) - 1,...
        ' ', market_attribute.train.upblue(id) - 1,...
        ' ', market_attribute.train.upgreen(id) - 1,...
        ' ', market_attribute.train.upgray(id) - 1,...
        ' ', market_attribute.train.uppurple(id) - 1,...
        ' ', market_attribute.train.upred(id) - 1,...
        ' ', market_attribute.train.upwhite(id) - 1,...
        ' ', market_attribute.train.upyellow(id) - 1,...
        ' ', market_attribute.train.clothes(id) - 1,...
        ' ', market_attribute.train.down(id) - 1,...
        ' ', market_attribute.train.up(id) - 1,...
        ' ', market_attribute.train.hair(id) - 1,...
        ' ', market_attribute.train.hat(id) - 1,...
        ' ', market_attribute.train.gender(id) - 1);
    
end
fclose(txt);
